<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('allowance_types');
        Schema::create('allowance_types', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->integer('is_active')->default(1);
            $table->timestamps();
            $table->unique(['name'], 'allowance_types_name_unique');
        });
        Schema::dropIfExists('cache');
        Schema::create('cache', function (Blueprint $table) {
            $table->string('key')->primary();
            $table->text('value');
            $table->integer('expiration');
            $table->index(['expiration'], 'cache_expiration_index');
        });
        Schema::dropIfExists('cache_locks');
        Schema::create('cache_locks', function (Blueprint $table) {
            $table->string('key')->primary();
            $table->string('owner');
            $table->integer('expiration');
            $table->index(['expiration'], 'cache_locks_expiration_index');
        });
        Schema::dropIfExists('clients');
        Schema::create('clients', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('contact_name')->nullable();
            $table->string('email')->nullable();
            $table->string('phone')->nullable();
            $table->text('address')->nullable();
            $table->text('notes')->nullable();
            $table->timestamps();
        });
        Schema::dropIfExists('equipment');
        Schema::create('equipment', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('serial_number')->nullable();
            $table->string('condition')->default('good');
            $table->timestamps();
        });
        Schema::dropIfExists('failed_jobs');
        Schema::create('failed_jobs', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('uuid');
            $table->text('connection');
            $table->text('queue');
            $table->text('payload');
            $table->text('exception');
            $table->timestamp('failed_at')->useCurrent();
            $table->unique(['uuid'], 'failed_jobs_uuid_unique');
        });
        Schema::dropIfExists('holidays');
        Schema::create('holidays', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->date('date');
            $table->text('description')->nullable();
            $table->integer('is_active')->default(1);
            $table->timestamps();
            $table->index(['date', 'is_active'], 'holidays_date_is_active_index');
            $table->unique(['date'], 'holidays_date_unique');
        });
        Schema::dropIfExists('job_batches');
        Schema::create('job_batches', function (Blueprint $table) {
            $table->string('id')->primary();
            $table->string('name');
            $table->integer('total_jobs');
            $table->integer('pending_jobs');
            $table->integer('failed_jobs');
            $table->text('failed_job_ids');
            $table->text('options')->nullable();
            $table->integer('cancelled_at')->nullable();
            $table->integer('finished_at')->nullable();
            $table->timestamp('created_at')->nullable();
        });
        Schema::dropIfExists('jobs');
        Schema::create('jobs', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('queue');
            $table->text('payload');
            $table->integer('attempts');
            $table->integer('reserved_at')->nullable();
            $table->integer('available_at');
            $table->timestamp('created_at')->nullable();
            $table->index(['queue'], 'jobs_queue_index');
        });
        Schema::dropIfExists('notifications');
        Schema::create('notifications', function (Blueprint $table) {
            $table->string('id')->primary();
            $table->string('type');
            $table->string('notifiable_type');
            $table->integer('notifiable_id');
            $table->text('data');
            $table->timestamp('read_at')->nullable();
            $table->timestamps();
            $table->index(['notifiable_type', 'notifiable_id'], 'notifications_notifiable_type_notifiable_id_index');
        });
        Schema::dropIfExists('password_reset_tokens');
        Schema::create('password_reset_tokens', function (Blueprint $table) {
            $table->string('email')->primary();
            $table->string('token');
            $table->timestamp('created_at')->nullable();
        });
        Schema::dropIfExists('permissions');
        Schema::create('permissions', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('label')->nullable();
            $table->timestamps();
            $table->unique(['name'], 'permissions_name_unique');
        });
        Schema::dropIfExists('personal_access_tokens');
        Schema::create('personal_access_tokens', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('tokenable_type');
            $table->integer('tokenable_id');
            $table->text('name');
            $table->string('token');
            $table->text('abilities')->nullable();
            $table->timestamp('last_used_at')->nullable();
            $table->timestamp('expires_at')->nullable();
            $table->timestamps();
            $table->index(['tokenable_type', 'tokenable_id'], 'personal_access_tokens_tokenable_type_tokenable_id_index');
            $table->unique(['token'], 'personal_access_tokens_token_unique');
            $table->index(['expires_at'], 'personal_access_tokens_expires_at_index');
        });
        Schema::dropIfExists('roles');
        Schema::create('roles', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('label')->nullable();
            $table->timestamps();
            $table->unique(['name'], 'roles_name_unique');
        });
        Schema::dropIfExists('sessions');
        Schema::create('sessions', function (Blueprint $table) {
            $table->string('id')->primary();
            $table->integer('user_id')->nullable();
            $table->string('ip_address')->nullable();
            $table->text('user_agent')->nullable();
            $table->text('payload');
            $table->integer('last_activity');
            $table->index(['user_id'], 'sessions_user_id_index');
            $table->index(['last_activity'], 'sessions_last_activity_index');
        });
        Schema::dropIfExists('settings');
        Schema::create('settings', function (Blueprint $table) {
            $table->string('key')->primary();
            $table->text('value')->nullable();
            $table->timestamps();
        });
        Schema::dropIfExists('users');
        Schema::create('users', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('email');
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->string('remember_token')->nullable();
            $table->string('phone')->nullable();
            $table->string('fcm_token')->nullable();
            $table->string('username')->nullable();
            $table->string('pin')->nullable();
            $table->string('avatar_url')->nullable();
            $table->integer('is_permanent_employee')->default(0);
            $table->text('homepage_preferences')->nullable();
            $table->text('address')->nullable();
            $table->string('emergency_contact')->nullable();
            $table->timestamps();
            $table->unique(['email'], 'users_email_unique');
            $table->unique(['username'], 'users_username_unique');
        });
        Schema::dropIfExists('vehicles');
        Schema::create('vehicles', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('registration_number')->nullable();
            $table->integer('capacity')->nullable();
            $table->string('status')->default('available');
            $table->text('notes')->nullable();
            $table->timestamps();
        });
        Schema::dropIfExists('permission_role');
        Schema::create('permission_role', function (Blueprint $table) {
            $table->integer('permission_id');
            $table->integer('role_id');
            $table->primary(['permission_id', 'role_id']);
            $table->foreign('permission_id')->references('id')->on('permissions')->onDelete('cascade');
            $table->foreign('role_id')->references('id')->on('roles')->onDelete('cascade');
        });
        Schema::dropIfExists('activity_logs');
        Schema::create('activity_logs', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('user_id')->nullable();
            $table->string('action');
            $table->string('model_type')->nullable();
            $table->integer('model_id')->nullable();
            $table->text('old_data')->nullable();
            $table->text('new_data')->nullable();
            $table->timestamp('timestamp');
            $table->string('ip_address')->nullable();
            $table->text('user_agent')->nullable();
            $table->timestamps();
            $table->index(['model_type', 'model_id'], 'activity_logs_model_type_model_id_index');
            $table->index(['timestamp'], 'activity_logs_timestamp_index');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('set null');
        });
        Schema::dropIfExists('audit_logs');
        Schema::create('audit_logs', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('user_id')->nullable();
            $table->string('method');
            $table->string('path');
            $table->string('full_url')->nullable();
            $table->string('source')->default('web');
            $table->string('ip_address')->nullable();
            $table->text('user_agent')->nullable();
            $table->integer('response_status')->nullable();
            $table->timestamps();
            $table->index(['user_id'], 'audit_logs_user_id_index');
            $table->index(['created_at'], 'audit_logs_created_at_index');
            $table->index(['source'], 'audit_logs_source_index');
            $table->index(['user_id', 'created_at'], 'audit_logs_user_id_created_at_index');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('set null');
        });
        Schema::dropIfExists('daily_office_checkins');
        Schema::create('daily_office_checkins', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('user_id');
            $table->date('date');
            $table->timestamp('checkin_time');
            $table->decimal('latitude', 14, 4)->nullable();
            $table->decimal('longitude', 14, 4)->nullable();
            $table->timestamp('checkout_time')->nullable();
            $table->decimal('total_hours', 14, 4)->nullable();
            $table->decimal('extra_hours', 14, 4)->nullable();
            $table->integer('is_sunday')->default(0);
            $table->integer('is_holiday')->default(0);
            $table->string('holiday_name')->nullable();
            $table->timestamps();
            $table->unique(['user_id', 'date'], 'daily_office_checkins_user_date_unique');
            $table->index(['date'], 'daily_office_checkins_date_index');
            $table->index(['user_id', 'date'], 'daily_office_checkins_user_id_date_index');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
        });
        Schema::dropIfExists('events');
        Schema::create('events', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->text('description')->nullable();
            $table->date('date');
            $table->text('start_time');
            $table->text('expected_end_time')->nullable();
            $table->string('location_name')->nullable();
            $table->decimal('latitude', 14, 4)->nullable();
            $table->decimal('longitude', 14, 4)->nullable();
            $table->integer('geofence_radius')->default(100);
            $table->integer('team_leader_id')->nullable();
            $table->string('status')->default('created');
            $table->integer('created_by_id')->nullable();
            $table->timestamp('ended_at')->nullable();
            $table->integer('ended_by_id')->nullable();
            $table->text('end_comment')->nullable();
            $table->integer('client_id')->nullable();
            $table->date('end_date')->nullable();
            $table->decimal('daily_allowance', 14, 4)->nullable();
            $table->timestamp('closed_at')->nullable();
            $table->integer('closed_by')->nullable();
            $table->text('closing_comment')->nullable();
            $table->integer('per_diem_enabled')->default(0);
            $table->timestamps();
            $table->foreign('client_id')->references('id')->on('clients')->onDelete('set null');
            $table->foreign('created_by_id')->references('id')->on('users')->onDelete('set null');
            $table->foreign('team_leader_id')->references('id')->on('users')->onDelete('set null');
            $table->foreign('ended_by_id')->references('id')->on('users')->onDelete('set null');
            $table->foreign('closed_by')->references('id')->on('users')->onDelete('set null');
        });
        Schema::dropIfExists('role_user');
        Schema::create('role_user', function (Blueprint $table) {
            $table->integer('role_id');
            $table->integer('user_id');
            $table->primary(['role_id', 'user_id']);
            $table->foreign('role_id')->references('id')->on('roles')->onDelete('cascade');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
        });
        Schema::dropIfExists('time_off_requests');
        Schema::create('time_off_requests', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('user_id');
            $table->date('start_date');
            $table->date('end_date');
            $table->text('reason')->nullable();
            $table->string('status')->default('pending');
            $table->integer('processed_by')->nullable();
            $table->timestamp('processed_at')->nullable();
            $table->text('notes')->nullable();
            $table->timestamps();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->foreign('processed_by')->references('id')->on('users')->onDelete('set null');
        });
        Schema::dropIfExists('communications');
        Schema::create('communications', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('sent_by_id');
            $table->string('subject');
            $table->text('body');
            $table->string('recipient_scope');
            $table->integer('event_id')->nullable();
            $table->integer('send_as_message')->default(1);
            $table->integer('send_as_email')->default(0);
            $table->timestamp('sent_at')->nullable();
            $table->timestamps();
            $table->foreign('sent_by_id')->references('id')->on('users')->onDelete('cascade');
            $table->foreign('event_id')->references('id')->on('events')->onDelete('set null');
        });
        Schema::dropIfExists('event_allowances');
        Schema::create('event_allowances', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('event_id');
            $table->integer('crew_id');
            $table->integer('allowance_type_id');
            $table->decimal('amount', 14, 4);
            $table->string('description')->nullable();
            $table->integer('recorded_by');
            $table->timestamp('recorded_at')->nullable();
            $table->string('status')->default('pending');
            $table->integer('approved_by')->nullable();
            $table->timestamp('approved_at')->nullable();
            $table->timestamp('paid_at')->nullable();
            $table->timestamps();
            $table->index(['event_id', 'status'], 'event_allowances_event_id_status_index');
            $table->index(['crew_id', 'status'], 'event_allowances_crew_id_status_index');
            $table->unique(['event_id', 'crew_id', 'allowance_type_id', 'recorded_at'], 'event_allowances_dedupe_key');
            $table->foreign('event_id')->references('id')->on('events')->onDelete('cascade');
            $table->foreign('crew_id')->references('id')->on('users')->onDelete('cascade');
            $table->foreign('allowance_type_id')->references('id')->on('allowance_types');
            $table->foreign('recorded_by')->references('id')->on('users');
            $table->foreign('approved_by')->references('id')->on('users')->onDelete('set null');
        });
        Schema::dropIfExists('event_checklist_items');
        Schema::create('event_checklist_items', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('event_id');
            $table->string('type');
            $table->integer('source_id')->nullable();
            $table->string('label');
            $table->integer('sort_order')->default(0);
            $table->integer('is_checked')->default(0);
            $table->timestamp('checked_at')->nullable();
            $table->integer('checked_by_id')->nullable();
            $table->timestamps();
            $table->foreign('event_id')->references('id')->on('events')->onDelete('cascade');
            $table->foreign('checked_by_id')->references('id')->on('users')->onDelete('set null');
        });
        Schema::dropIfExists('event_equipment');
        Schema::create('event_equipment', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('event_id');
            $table->integer('equipment_id');
            $table->integer('confirmed_by')->nullable();
            $table->timestamp('confirmed_at')->nullable();
            $table->text('notes')->nullable();
            $table->timestamps();
            $table->unique(['event_id', 'equipment_id'], 'event_equipment_event_id_equipment_id_unique');
            $table->foreign('event_id')->references('id')->on('events')->onDelete('cascade');
            $table->foreign('equipment_id')->references('id')->on('equipment')->onDelete('cascade');
            $table->foreign('confirmed_by')->references('id')->on('users')->onDelete('set null');
        });
        Schema::dropIfExists('event_expenses');
        Schema::create('event_expenses', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('event_id');
            $table->integer('user_id');
            $table->integer('used_company_transport')->default(0);
            $table->decimal('cab_amount', 14, 4)->default(0);
            $table->decimal('parking_fee', 14, 4)->default(0);
            $table->timestamps();
            $table->unique(['event_id', 'user_id'], 'event_expenses_event_id_user_id_unique');
            $table->foreign('event_id')->references('id')->on('events')->onDelete('cascade');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
        });
        Schema::dropIfExists('event_meals');
        Schema::create('event_meals', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('user_id');
            $table->integer('event_id');
            $table->integer('breakfast')->default(0);
            $table->integer('lunch')->default(0);
            $table->integer('dinner')->default(0);
            $table->timestamps();
            $table->unique(['event_id', 'user_id'], 'event_meals_event_id_user_id_unique');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->foreign('event_id')->references('id')->on('events')->onDelete('cascade');
        });
        Schema::dropIfExists('event_notes');
        Schema::create('event_notes', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('event_id');
            $table->integer('user_id');
            $table->text('note');
            $table->timestamps();
            $table->foreign('event_id')->references('id')->on('events')->onDelete('cascade');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
        });
        Schema::dropIfExists('event_payments');
        Schema::create('event_payments', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('event_id');
            $table->integer('user_id');
            $table->decimal('hours', 14, 4)->default(0);
            $table->decimal('per_diem', 14, 4)->default(0);
            $table->decimal('allowances', 14, 4)->default(0);
            $table->decimal('total_amount', 14, 4)->default(0);
            $table->string('status')->default('pending');
            $table->integer('approved_by')->nullable();
            $table->timestamp('approved_at')->nullable();
            $table->text('rejection_reason')->nullable();
            $table->string('purpose')->nullable();
            $table->date('payment_date')->nullable();
            $table->timestamps();
            $table->unique(['event_id', 'user_id'], 'event_payments_event_id_user_id_unique');
            $table->foreign('event_id')->references('id')->on('events')->onDelete('cascade');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->foreign('approved_by')->references('id')->on('users')->onDelete('set null');
        });
        Schema::dropIfExists('event_user');
        Schema::create('event_user', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('event_id');
            $table->integer('user_id');
            $table->string('role_in_event')->nullable();
            $table->timestamp('checkin_time')->nullable();
            $table->timestamp('checkout_time')->nullable();
            $table->decimal('total_hours', 14, 4)->nullable();
            $table->decimal('checkin_latitude', 14, 4)->nullable();
            $table->decimal('checkin_longitude', 14, 4)->nullable();
            $table->decimal('extra_hours', 14, 4)->nullable();
            $table->integer('is_sunday')->default(0);
            $table->integer('is_holiday')->default(0);
            $table->string('holiday_name')->nullable();
            $table->integer('is_paused')->default(0);
            $table->timestamp('pause_start_time')->nullable();
            $table->timestamp('pause_end_time')->nullable();
            $table->integer('pause_duration')->default(0);
            $table->integer('paused_by')->nullable();
            $table->string('pause_reason')->nullable();
            $table->string('transport_type')->nullable();
            $table->decimal('transport_amount', 14, 4)->nullable();
            $table->integer('transport_recorded_by')->nullable();
            $table->timestamp('transport_recorded_at')->nullable();
            $table->timestamps();
            $table->unique(['event_id', 'user_id'], 'event_user_event_id_user_id_unique');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->foreign('event_id')->references('id')->on('events')->onDelete('cascade');
            $table->foreign('paused_by')->references('id')->on('users')->onDelete('set null');
            $table->foreign('transport_recorded_by')->references('id')->on('users')->onDelete('set null');
        });
        Schema::dropIfExists('event_vehicle');
        Schema::create('event_vehicle', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('event_id');
            $table->integer('vehicle_id');
            $table->integer('driver_id')->nullable();
            $table->text('notes')->nullable();
            $table->timestamps();
            $table->unique(['event_id', 'vehicle_id'], 'event_vehicle_event_id_vehicle_id_unique');
            $table->foreign('event_id')->references('id')->on('events')->onDelete('cascade');
            $table->foreign('vehicle_id')->references('id')->on('vehicles')->onDelete('cascade');
            $table->foreign('driver_id')->references('id')->on('users')->onDelete('set null');
        });
        Schema::dropIfExists('reminder_logs');
        Schema::create('reminder_logs', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('event_id');
            $table->integer('user_id');
            $table->string('type');
            $table->string('channel');
            $table->timestamp('sent_at');
            $table->timestamps();
            $table->index(['event_id', 'user_id', 'type'], 'reminder_logs_event_id_user_id_type_index');
            $table->foreign('event_id')->references('id')->on('events')->onDelete('cascade');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
        });
        Schema::dropIfExists('tasks');
        Schema::create('tasks', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('title');
            $table->text('description')->nullable();
            $table->integer('event_id')->nullable();
            $table->integer('created_by')->nullable();
            $table->string('priority')->default('medium');
            $table->date('due_date')->nullable();
            $table->string('status')->default('pending');
            $table->text('notes')->nullable();
            $table->timestamps();
            $table->foreign('event_id')->references('id')->on('events')->onDelete('set null');
            $table->foreign('created_by')->references('id')->on('users')->onDelete('set null');
        });
        Schema::dropIfExists('time_off_request_attachments');
        Schema::create('time_off_request_attachments', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('time_off_request_id');
            $table->string('path');
            $table->string('original_name')->nullable();
            $table->timestamps();
            $table->foreign('time_off_request_id')->references('id')->on('time_off_requests')->onDelete('cascade');
        });
        Schema::dropIfExists('task_comments');
        Schema::create('task_comments', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('task_id');
            $table->integer('user_id');
            $table->text('body');
            $table->timestamps();
            $table->foreign('task_id')->references('id')->on('tasks')->onDelete('cascade');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
        });
        Schema::dropIfExists('task_user');
        Schema::create('task_user', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('task_id');
            $table->integer('user_id');
            $table->timestamps();
            $table->unique(['task_id', 'user_id'], 'task_user_task_id_user_id_unique');
            $table->foreign('task_id')->references('id')->on('tasks')->onDelete('cascade');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
        });
        Schema::enableForeignKeyConstraints();
    }

    public function down(): void
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('task_user');
        Schema::dropIfExists('task_comments');
        Schema::dropIfExists('time_off_request_attachments');
        Schema::dropIfExists('tasks');
        Schema::dropIfExists('reminder_logs');
        Schema::dropIfExists('event_vehicle');
        Schema::dropIfExists('event_user');
        Schema::dropIfExists('event_payments');
        Schema::dropIfExists('event_notes');
        Schema::dropIfExists('event_meals');
        Schema::dropIfExists('event_expenses');
        Schema::dropIfExists('event_equipment');
        Schema::dropIfExists('event_checklist_items');
        Schema::dropIfExists('event_allowances');
        Schema::dropIfExists('communications');
        Schema::dropIfExists('time_off_requests');
        Schema::dropIfExists('role_user');
        Schema::dropIfExists('events');
        Schema::dropIfExists('daily_office_checkins');
        Schema::dropIfExists('audit_logs');
        Schema::dropIfExists('activity_logs');
        Schema::dropIfExists('permission_role');
        Schema::dropIfExists('vehicles');
        Schema::dropIfExists('users');
        Schema::dropIfExists('settings');
        Schema::dropIfExists('sessions');
        Schema::dropIfExists('roles');
        Schema::dropIfExists('personal_access_tokens');
        Schema::dropIfExists('permissions');
        Schema::dropIfExists('password_reset_tokens');
        Schema::dropIfExists('notifications');
        Schema::dropIfExists('jobs');
        Schema::dropIfExists('job_batches');
        Schema::dropIfExists('holidays');
        Schema::dropIfExists('failed_jobs');
        Schema::dropIfExists('equipment');
        Schema::dropIfExists('clients');
        Schema::dropIfExists('cache_locks');
        Schema::dropIfExists('cache');
        Schema::dropIfExists('allowance_types');
        Schema::enableForeignKeyConstraints();
    }
};
